# Generated by Django 6.0 on 2025-12-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False)),
                ('room_capacity', models.IntegerField(default=0)),
                ('room_type', models.CharField(max_length=100)),
                ('room_price', models.IntegerField(default=0)),
                ('room_status', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
